name: 'Terraform CD'

on:
  push:
    branches:
      # The CD workflow should run whenever code is pushed to these branches
      - staging
      - prod

jobs:
  terraform:
    name: 'Terraform Deployment'
    runs-on: ubuntu-latest

    # Conditional environment selection based on the branch
    environment:
      ${{ github.ref == 'refs/heads/staging' && 'staging' || '' }}
      ${{ github.ref == 'refs/heads/prod' && 'prod' || '' }}

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Init
        id: init
        run: terraform init

      - name: Terraform Plan
        id: plan
        run: terraform plan -no-color

      - name: Terraform Apply
        if: github.ref == 'refs/heads/staging' || github.ref == 'refs/heads/prod'
        run: terraform apply -auto-approve
